language: c++
jobs:
  include:
    - compiler: gcc
      os: linux
      dist: bionic
    - compiler: clang
      os: linux
      dist: bionic
    - compiler: gcc
      os: linux
      dist: xenial
    - compiler: clang
      os: linux
      dist: xenial

addons:
  apt:
    packages:
      - libspf2-dev
      - doxygen
      - graphviz
  homebrew:
    packages:
      - libintl
      - gettext
      - openssl
      - doxygen
      - graphviz

script:
  - mkdir build
  - pushd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install-dir
  - make install
  - find $PWD/install-dir
  - popd
