#!/bin/bash
# Startup script for hermes
#
# chkconfig: 3 95 05
# description: hermes

# Source function library.
. /etc/rc.d/init.d/functions

prog=hermes
configfile=/etc/hermes/hermesrc

start() {
  echo -n $"Starting $prog: "
  daemon --check=$prog /usr/bin/hermes $configfile
  RETVAL=$?
  echo
}

stop() {
  echo -n $"Stopping $prog: "
  killproc $prog
  RETVAL=$?
  echo
}

safestop() {
  echo -n $"Stopping $prog(will process pending connections):"
  killproc $prog -INT
  rm /var/run/$prog.pid
  RETVAL=$?
  echo
}

case "$1" in
  start)
    start
    ;;

  stop)
    stop
    ;;

  restart)
    safestop
    sleep 2
    start
    ;;
  condrestart)
    if test "x`pidfileofproc $prog`" != x; then
    stop
    start
    fi
    ;;

  *)
    echo $"Usage: $0 {start|stop|restart|condrestart}"
    exit 1

esac

exit $RETVAL
